main:	bubble_sort.cpp count_sort.cpp heap_sort.cpp insertion_sort.cpp main.cpp merge_sort.cpp quick_sort.cpp radix_sort.cpp selection_sort.cpp shell_sort.cpp
	g++  	bubble_sort.cpp count_sort.cpp heap_sort.cpp insertion_sort.cpp main.cpp merge_sort.cpp quick_sort.cpp radix_sort.cpp selection_sort.cpp shell_sort.cpp -o main
